openapi: "3.0.3"

info:
  title: "Iced Latte Favorite List API"
  description: "The Iced Latte Favorite List API allows users to save, retrieve, and manage their favorite items."
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://iced-latte.uk/backend"
    description: "Production server"

tags:
  - name: "Favorite Products"
    description: "Operations for managing favorite products."

paths:
  /api/v1/favorites/{productId}:
    delete:
      tags:
        - "Favorite Products"
      summary: "Remove a product by ID from favorite product list."
      description: "Removes a product from the user's favorite list using the product's unique identifier."
      operationId: "removeProductFromFavorite"
      parameters:
        - name: "productId"
          in: "path"
          required: true
          description: "The unique identifier of the product."
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "The product was successfully removed from favorites."
        "400":
          description: "The provided input is invalid."
        "401":
          description: "Unauthorized access."
        "404":
          description: "The specified favorite product was not found."
        "500":
          description: "An internal server error occurred."

  /api/v1/favorites:
    get:
      tags:
        - "Favorite Products"
      summary: "Retrieve all favorite products"
      description: "Fetches the list of all products marked as favorites by the authenticated user."
      operationId: "getListOfFavoriteProducts"
      responses:
        "200":
          description: "A list of favorite products was successfully retrieved."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfFavoriteProductsDto"
        "401":
          description: "Unauthorized access."
        "404":
          description: "The favorite products list is empty."
        "500":
          description: "An internal server error occurred."

    post:
      tags:
        - "Favorite Products"
      summary: "Add products to favorites"
      description: "Adds one or more products to the user's favorite list."
      operationId: "addListOfFavoriteProducts"
      requestBody:
        description: "A list of product IDs to be added to the user's favorite list."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListOfFavoriteProducts"
      responses:
        "200":
          description: "The products were successfully added to favorites."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfFavoriteProductsDto"
        "400":
          description: "The provided input is invalid."
        "401":
          description: "Unauthorized access."
        "500":
          description: "An internal server error occurred."

components:
  schemas:

    ListOfFavoriteProducts:
      type: object
      description: "A list of product IDs to be added to the user's favorite list."
      properties:
        productIds:
          type: array
          description: "An array of unique identifiers for the products."
          items:
            type: string
            format: uuid
      required:
        - productIds

    ListOfFavoriteProductsDto:
      type: object
      description: "A list of products marked as favorites by the user."
      properties:
        products:
          type: array
          description: "An array of product details for the favorite products."
          items:
            $ref: "product-openapi.yaml#/components/schemas/ProductInfoDto"
      required:
        - productsDto