openapi: "3.0.3"

info:
  title: "Iced Latte Order API"
  description: "API for managing orders, including retrieving and placing orders. Supports filtering orders by status and provides detailed order information."
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://iced-latte.uk/backend"
    description: "Production server"

tags:
  - name: "Orders"
    description: "Operations related to orders."

paths:
  /api/v1/orders:
    get:
      tags:
        - "Orders"
      summary: "Retrieve orders for the authorized user based on status"
      description: "Fetches all orders for the authenticated user, optionally filtered by status codes."
      operationId: "getOrders"
      parameters:
        - name: "status"
          description: "Filter orders by status. Multiple status codes can be provided as an array."
          in: "query"
          required: false
          schema:
            type: "array"
            items:
              $ref: "#/components/schemas/OrderStatus"
      responses:
        "200":
          description: "List of orders successfully retrieved."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/OrderDto"
        "401":
          description: "Unauthorized access."
        "404":
          description: "No orders found matching the specified criteria."
        "500":
          description: "Internal server error."

    post:
      tags:
        - "Orders"
      summary: "Place a new order for the authorized user"
      description: "Creates a new order for the authenticated user. Requires address and recipient information."
      operationId: "createOrder"
      responses:
        "200":
          description: "Order successfully placed."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDto"
        "400":
          description: "Invalid input data."
        "401":
          description: "Unauthorized access."
        "500":
          description: "Internal server error."

components:
  schemas:
    OrderStatus:
      type: string
      description: "The status of an order."
      enum:
        - CREATED
        - PAID
        - DELIVERY
        - FINISHED

    CreateNewOrderRequestDto:
      type: "object"
      description: "Details required to create a new order."
      required:
        - address
        - recipientName
        - recipientSurname
      properties:
        address:
          $ref: "./user-openapi.yaml#/components/schemas/AddressDto"
        recipientName:
          type: "string"
          description: "Name of the order recipient. Can be different from the user's name."
        recipientSurname:
          type: "string"
          description: "Surname of the order recipient. Can be different from the user's surname."

    OrderDto:
      type: "object"
      description: "Represents an order in the system."
      required:
        - id
        - status
        - createdAt
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Unique identifier for the order."
        status:
          $ref: '#/components/schemas/OrderStatus'
        createdAt:
          type: "string"
          format: "date-time"
          description: "The date and time when the order was created."
